---
title: "BIOL4800/6220_Fall2022_RTutorial"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

# R Basic

## Introduction

R as a calculator

```{r}
1 + 100 
```
```{r}
2^2
```


```{r}
7/2
```


```{r}
4-1
```
```{r}
2*2
```
```{r}
3+5*2
```
```{r}
2e2
```
```{r}
2/10000
```
```{r}
sin(1)
```
```{r}
log
```

```{r}
exp(0)
```
```{r}
1==1
```
```{r}
1>=1
```
```{r}
1<=1
```
```{r}
1!=2
```
```{r}
x <- 10
x
```
```{r}
x+x
```
```{r}
x^2
```
```{r}
y <- x+x
y
```
```{r}
1:5
```
```{r}
2^(1:5)
```

```{r}
v <-1:5
v
```

```{r}
log10(v)
```
```{r}
ls()
```
```{r}
rm(v)
```

```{r}
ls()
```

## Package Management

```{r}
#installed.packages()
```
```{r}
#install.packages("vegan", dependencies=TRUE)
```
```{r}
#library(vegan)
```

```{r}
#remove.packages("vegan")
```

## Project Managment

1. Set up management structure (i.e., "data, "src", "results", "doc")
2. Discuss avoiding redundancy of files
3. Make sure ot use version control (i.e., Git)

## Getting Help

```{r}
?plot
```


```{r}
help(plot)
```


```{r}
?"<-"
```


```{r}
vignette("FAQ-vegan")
```

```{r}
vignette
```

## Data and their fromats
```{r}
cats <- data.frame(coat =c("calico","black","tabby"),
                  weight = c(2.1,5,3.2),
                  likes_string = c(1,0,1))
```

```{r}
cats
```
```{r}
getwd()
```

```{r}
write.csv(cats, file = "./data/cats.csv")
```

```{r}
cats <- read.csv("./data/cats.csv")
```

```{r}
cats$coat
```

```{r}
cats$weight*10
```
```{r}
log(cats$weight)
```
```{r}
logweight <- log(cats$weight)
cats <- cbind(cats, logweight)
```
```{r}
cats
```
```{r}
paste("my cat is ", cats$coat, ", and it weighs ", cats$weight, "kg.", sep=)
```

### Data Types

```{r}
typeof(cats$coat)
```


```{r}
typeof(cats$weight)
```


```{r}
typeof(cats$likes_string)
```
```{r}
typeof(3.14159)
```


```{r}
typeof(1i)
```


```{r}
typeof(TRUE)
```


```{r}
typeof(T)
typeof(F)
```


```{r}
typeof(cats)
```


```{r}
class(cats)
```
```{r}
file.show("./data/cats/.csv")
```
```{r}

typeof()
```

```{r}
cats$likes_string
```
```{r}
ab <- c ("a","b")
ab
```

```{r}
1:10
```


```{r}
z <- seq (10)
head(z, n=3)
```


```{r}
class(z)
```


```{r}
typeof(z)
```


```{r}
seq(1,100, by=5)
```
### Data Frames

```{r}
cats
```


```{r}
str(cats)
```

```{r}
coats <- c("tabby", "tortoiseshell", "tortoiseshell", "black", "tabby")
coats
```

```{r}
class(coats)
```

```{r}
factor(coats)
```
```{r}
categories <- factor(coats)
class(coats)
class(categories)
```

```{r}
str(categories)
```
### Lists

```{r}
list_example <- list(title="Numbers", numbers = 1:10, data=TRUE)
list_example
```


```{r}
another_list <- list(1,"a", TRUE, 1+1i)
```

```{r}
typeof(list_example)
clas(list_example)
```
```{r}
typeof(cats)
class(cats)
```
```{r}
data.frame(list_example)
```

```{r}
cats
```

```{r}
cats[,3]
```

```{r}
cats[2:3,c(1,3)]
```

